/**
 * Table of contents entries with real page numbers.
 *
 * Captured from an actual pagination pass rather than left to a TOC field,
 * so the contents page is correct in ANY reader — not just Microsoft Word.
 * A TOC field renders as 'right-click to update', or as an empty box, in
 * browsers, phone viewers and Google Docs.
 */
export const TOC_ENTRIES = [
  [1, 4, 'Deliverables'],
  [2, 4, 'Evaluating it in five minutes'],
  [1, 5, '1.  Executive summary'],
  [2, 5, '1.1  The problem, precisely'],
  [2, 5, '1.2  The governing design decision'],
  [2, 5, '1.3  What was built'],
  [1, 6, '2.  System architecture'],
  [2, 6, '2.1  Why a modular monolith, and one genuine split'],
  [2, 6, '2.2  Leader election, and why it is structural'],
  [2, 6, '2.3  Job discovery: push for latency, polling for correctness'],
  [1, 8, '3.  Database design'],
  [2, 8, '3.1  The split that matters most'],
  [2, 9, '3.2  The claim index'],
  [2, 9, '3.3  Cascade rules are chosen per relationship'],
  [2, 9, '3.4  Three deliberate denormalisations'],
  [2, 10, '3.5  Invalid states are unrepresentable'],
  [1, 11, '4.  Atomic job claiming'],
  [2, 11, '4.1  The problem'],
  [2, 11, '4.2  Approaches considered'],
  [2, 11, '4.3  How SKIP LOCKED works'],
  [2, 11, '4.4  The claim query'],
  [2, 12, '4.5  Priority: the trap in the brief'],
  [1, 14, '5.  Job lifecycle and crash recovery'],
  [2, 14, '5.1  Where "Failed" went'],
  [2, 14, '5.2  The conditional write'],
  [2, 14, '5.3  Crash recovery'],
  [2, 15, '5.4  Heartbeats and the timing invariant'],
  [2, 16, '5.5  Graceful shutdown'],
  [1, 17, '6.  Retries and backoff'],
  [2, 17, '6.1  The three strategies'],
  [2, 17, '6.2  Jitter is not decoration'],
  [2, 18, '6.3  The worker does not sleep'],
  [2, 18, '6.4  Not every failure deserves five attempts'],
  [1, 18, '7.  Dead letter queue'],
  [2, 18, '7.1  What happens, transactionally'],
  [2, 18, '7.2  Triage by error signature'],
  [2, 18, '7.3  Replay creates a new job'],
  [1, 20, '8.  Idempotency'],
  [2, 20, '8.1  Duplicate submission — fully solvable'],
  [2, 20, '8.2  Duplicate execution — not fully solvable'],
  [1, 21, '9.  Design decisions and trade-offs'],
  [2, 22, '9.11  Deliberately not built'],
  [1, 23, '10.  API design'],
  [2, 23, '10.1  Conventions'],
  [2, 23, '10.2  No POST /workers'],
  [1, 24, '11.  Testing strategy'],
  [2, 24, '11.1  Unit tests — 85, no database, under one second'],
  [2, 24, '11.2  Concurrency tests — the gate'],
  [2, 24, '11.3  Defects found by this discipline'],
  [1, 26, '12.  Running the system'],
  [2, 26, '12.1  One command'],
  [2, 26, '12.2  The demonstration'],
  [2, 26, '12.3  Verified state'],
  [2, 27, '12.4  Where the detail lives'],
];
